set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

# Сменить префикс на Ctrl-a (как в GNU screen)
unbind C-b
set-option -g prefix C-Space
bind-key C-Space send-prefix

# Vi-стиль in copy-mode
setw -g mode-keys vi

# Быстрый перезагруз конфига: Prefix + r
bind r source-file ~/.tmux.conf \; display "Конфиг перезагружен!"

# Alt+hjkl as pane navigation
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# Shift Alt vim keys to switch windows
bind -n M-H previous-window
bind -n M-L next-window

# Set true color
# set -as terminal-features ",alacritty*:RGB"
# set-option -as terminal-overrides ",xterm*:Tc"

# Enable mouse support
set -g mouse on

# Start windows and panes at 1, not 0
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Set prefix
unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Set vi-mode
set-window-option -g mode-keys vi

# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Open panes in current directory
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g status-position top

run '~/.tmux/plugins/tpm/tpm'
